# Generated by Django 5.1 on 2024-08-27 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('seasons', models.IntegerField()),
                ('year', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('first_episode', models.DateTimeField(auto_now_add=True)),
                ('last_episode', models.DateTimeField(auto_now=True)),
                ('followed_by', models.ManyToManyField(related_name='followed_series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
