# Generated by Django 5.1 on 2024-08-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
