# Generated by Django 5.1 on 2024-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_serie_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serie',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serie',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
