# Generated by Django 5.1 on 2024-08-27 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('image_url', models.URLField(default='https://via.placeholder.com/150')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('release_at', models.DateTimeField(auto_now_add=True)),
                ('followed_by', models.ManyToManyField(related_name='followed_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
