# Generated by Django 5.1 on 2024-08-27 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='followed_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
